config/routes.rb
IWillWorkForGumbo::Application.routes.draw do

  get "pages/help"

  resources :jobs do
    member do
      post :notify_friend
    end
    collection do
      get :search
      get :limit
    end
    resources :bids
    resources :comments
    resources :assets

  end

  resources :members do
    resources :comments
  end
  resource :session
  resources :password_resets

  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  root :to => 'jobs#index'

end

app/models/bid.rb
class Bid < ActiveRecord::Base

  belongs_to :job
  
  validates :name, :email, :body, :bid_amount, :presence => {:message => 'cannot be empty'}
  
  validates :bid_amount, :numericality => true
  validate :job_should_be_published

  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]+\z/i, :message => "email format isn't right"
  
  def job_should_be_published
    errors.add(:job_id, "is not published yet") if job && !job.published?
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :load_job, :except => :destroy
  before_filter :authenticate, :only => :destroy

  def create
    @bid = @job.bids.new(bid_params)
    if @bid.save
      respond_to do |format|
        @notice =
        format.html {redirect_to @job, :notice => 'Your bid is recorded and the job owner was emailed your bid. Thank you!'}
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @job, :alert => 'Unable to record your bid!'}
        format.js {render 'fail_create.js' }
      end
    end
  end

  def edit
    if @job.bids.where('bid_selected = ?', 1).empty?
      @bid = @job.bids.find(params[:id])
    else
      format.html { redirect_to @job, :alert => 'Unable to record your bid!  Another bid was already selected.' }
    end
  end

  def update
    @job = current_member.jobs.find(params[:job_id])
    @bid = @job.bids.find(params[:id])
    respond_to do |format|
      if @bid.update_attributes(bid_params)
        format.html { redirect_to @job, :notice => 'Bid was successfully accepted.' }
        format.json { head :no_content }
      end
    end
  end


  def destroy
    @job = current_member.jobs.find(params[:job_id])
    @bid = @job.bids.find(params[:id])
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to @job, :notice => 'Bid has been removed!'}
      format.js
    end
  end



  private
    def load_job
      @job = Job.find(params[:job_id])
    end

    def bid_params
      params.require(:bid).permit(:name, :email, :body, :bid_selected, :bid_per_rate, :bid_amount)
    end
end

app/helpers/bids_helper.rb
module BidsHelper

end

app/views/bids/_bid.html.erb
<%= div_for bid do %>
	<h3>
		<% if bid.bid_selected? %>
			<span class = "bid_selected">
				<%= bid.email %> - <%= bid.name %>'s bid for&nbsp;<%= number_to_currency(bid.bid_amount) %>&nbsp;per&nbsp;<%= bid.bid_per_rate %>&nbsp;created on <%= bid.updated_at.strftime("%d %b. %Y")%>
				was accepted!
			</span>
		<% else %>
				<%= bid.email %> - <%=bid.name %>'s bid for&nbsp;<%= number_to_currency(bid.bid_amount) %>&nbsp;per&nbsp;<%= bid.bid_per_rate %>&nbsp;was created on <%= bid.updated_at.strftime("%d %b. %Y")%>
		<% end %>
	</h3>

		<% if bid.bid_selected? %>
			<span class = "bid_selected">
				<%= bid.body %>
			</span>
		<% else %>
				<%= bid.body %>
		<% end %>

		<% @selected = @job.bids.where('bid_selected = ?', 1).first %>
		<% if (@job.owned_by? current_member) && !bid.bid_selected? %>
  			<p><span class = "actions" >
			(Do you want to
			<%= link_to '(Remove)',
				job_bid_path(:job_id => @job, :id => bid),
				:confirm => 'Are you sure',
				:method => :delete, :remote => true
			%>
			<% if @selected.nil? %>
				or
				<%= link_to '(Accept)', edit_job_bid_path(:job_id => @job, :id => bid) %>
			<% end %>
			this bid?)
			</span></p>
		<% end %>




<% end %>

app/views/bids/create.js.erb
$('#bids').append("<%= escape_javascript(render(@bid)) %>");

$('#new_bid_link').slideDown();
$('#bid_cancel_link').slideDown();

app/views/bids/destroy.js.erb
$("#<%= dom_id(@bid) %>").remove()

app/views/bids/edit.html.erb
<%= form_for([@job, @bid]) do |f| %>

This bid was created on: <%= @bid.created_at.strftime("%d %b. %Y") %><br/ ><br />


<%= div_for @job do %>
	<h3>
		<%= @job.title %>
	</h3>
	Categories:
	<% @job.categories.each do |jobcat| %>
		<b><%= jobcat.name %></b>
	<% end %>
	&nbsp;Tags:
	<b><%= @job.excerpt %></b><br />
	<b><%= @job.bids.count %>&nbsp;Current&nbsp;Bids</b>
	<%= simple_format @job.body %>
<% end %>



	<div class="field">
		<%= f.label :name %>
		<%= @bid.name %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= @bid.email %>
	</div>

	<div class="field">
		<%= f.label "State Your Case" %>
		<%= @bid.body %>
	</div>

	<div class="field">
		<%= f.label "Accept Bid" %>
		<%= f.check_box :bid_selected %>
	</div>

 	<div class="actions">
	   <!-- %= submit_or_cancel(f) % -->
	    <%= f.submit 'Submit your acceptance!' %> or
		<%= link_to 'Simmer Just A Bit!', jobs_path %>
 	</div>


<% end %>

app/views/bids/edit.js.erb
$("<%= escape_javascript render(:file => 'bids/edit.html.erb') %>").insertAfter('#bids');
$('#edit_bid_2').slideDown();
$('#new_bid_link').hide();
$('#bid_cancel_link').hide();

app/views/bids/fail_create.js.erb
alert("<%= @bid.errors.full_messages.to_sentence %>");

app/views/bids/new.html.erb
<%= form_for [@job, @job.bids.new], :validate => true do |f| %>
	<br/>
	<h3>Place Your Bid On This Stuff</h3>
	<br />
	<div class="field">
		<%= f.label "Your name" %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label "Your email" %>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label "What ingredients and skills can you bring to the table?" %>
		<%= f.text_area :body %>
	</div>

<div>
	<div class="field">
		<%= f.label "Your bid in $$ " %>
		<%= f.text_field :bid_amount %>&nbsp;(Don't key $ or commas, Just use numbers i.e.  10 or 10.00)
	</div>

	<div class="field">
		<%= f.label "per" %>
		<%= f.select(:bid_per_rate, ['Job','Piece', 'Unit' , 'Hr.', 'Day', 'Week', 'Month', 'Year']) %>
	</div>
</div>

	<div class="actions">
    	<!-- %= submit_or_cancel(f) % -->
    	<%= submit_tag 'Bid On This Stuff' %> or
		<%= link_to 'Simmer Just A Bit!', '#', :onclick => "$('#new_bid').slideUp();$('#new_bid_link').slideDown();$('#bid_cancel_link').slideDown();" %>
  	</div>



<% end %>

app/views/bids/new.js.erb
$('#flash').html("<%= escape_javascript raw(flash_display) %>");
$("<%= escape_javascript render(:file => 'bids/new.html.erb') %>").insertBefore('#bids');
$("#new_bid").validate();
$("#new_bid").removeAttr("novalidate");
$('#new_bid').slideDown();
$('#new_bid_link').hide();
$('#job_cancel_link').hide();
$('#bid_cancel_link').hide();