config/routes.rb
IWillWorkForGumbo::Application.routes.draw do

  get "pages/help"

  resources :jobs do
    member do
      post :notify_friend
    end
    collection do
      get :search
      get :limit
    end
    resources :bids
    resources :comments
    resources :assets

  end

  resources :members do
    resources :comments
  end
  resource :session
  resources :password_resets

  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  root :to => 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base

  validates :title, :presence => true
  validates :body, :presence => {:message => "Stuff to be done - cannot be blank!"}

  belongs_to :member

  has_and_belongs_to_many :categories

  has_many :bids, :dependent => :destroy
  has_many :comments, as: :commentable
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, allow_destroy: true

  after_update :save_assets
#  acts_as_taggable


  scope :published, where("jobs.published_at IS NOT NULL")
  scope :draft, where("jobs.published_at IS NULL")
  scope :recent, lambda { published.where("jobs.published_at > ?", 1.week.ago.to_date) }
  scope :where_title, lambda { |term| where("jobs.title LIKE ?", "%#{term}%")}

  def new_asset_attributes=(asset_attributes)
    asset_attributes.each do |attributes|
      assets.build(attributes)
    end
  end

  def existing_asset_attributes=(asset_attributes)
    assets.reject(&:new_record?).each do |asset|
      attributes = asset_attributes[asset.id.to_s]
      if attributes
        asset.attributes = attributes
      else
        asset.delete(asset)
      end
    end
  end

  def save_assets
    assets.each do |asset|
      asset.save(:validate => false)
    end
  end

  def long_title
    "#{title} - #{published_at}"
  end

  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a? Member
    member == owner
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :authenticate, :except => [:index, :show, :notify_friend, :filter, :search]

  def search
    self.limit
    render :action => 'index'
  end

  # GET /jobs
  # GET /jobs.json
  def index
    self.limit
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    @commentable = @job
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
   @job = Job.new
   @ct = @job.assets.count
   (MAX_ASSETS - @ct).times {@job.assets.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = current_member.jobs.find(params[:id])
    @ct = @job.assets.count
    (MAX_ASSETS - @ct).times {@job.assets.build}

  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_member.jobs.new(job_params)
    @job.published_at = DateTime.now


    respond_to do |format|
      if @job.save

        format.html { redirect_to @job, notice: 'The stuff you want done was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update

    @job = current_member.jobs.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(job_params)
        format.html { redirect_to @job, notice: 'The stuff you want done was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = current_member.jobs.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def notify_friend
    @job = Job.find(params[:id])
    if (params[:name].size > 0 && params[:email].size > 0) and (valid_email?(params[:email]))
      Notifier.email_friend(@job, params[:name], params[:email]).deliver
      redirect_to @job, :notice => "Successfully sent this stuff to your friend"
    else
      redirect_to @job, :notice => 'Both Friend Name and Email Address Must be Present and Formatted Correctly in order to Send Email to a Friend! Try Again.'
    end
  end


  def limit
    search_condition = "%" + params[:keyword].to_s + "%"
    search_cat = params[:category].to_i
    search_keyword = params[:keyword].to_s

    if search_cat == 0

      if search_keyword > ""
        @jobs = Job.where('UPPER(title) LIKE UPPER(?) OR UPPER(body) LIKE UPPER(?) OR UPPER(excerpt) LIKE UPPER(?) OR UPPER(location) LIKE UPPER(?)', search_condition, search_condition, search_condition, search_condition).order(updated_at: :desc)
       # @jobs.order(updated_at: :desc)
        @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(4)
      else
        @jobs = Job.order(updated_at: :desc).page(params[:page]).per(4)
      end
    else
      @cat = Category.find(search_cat.to_i)
      @jobs = @cat.jobs.where('UPPER(title) LIKE UPPER(?) OR UPPER(body) LIKE UPPER(?) OR UPPER(excerpt) LIKE UPPER(?) OR UPPER(location) LIKE UPPER(?)', search_condition, search_condition, search_condition, search_condition).order(updated_at: :desc)
     # @jobs.order(updated_at: :desc)
      @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(4)
    end

  end

private
  def valid_email?(email)
    email.present? &&
     (email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i)
  end

  def job_params
#    params.require(:job).permit(:title, :body, :excerpt, :location, :categories, {:category_ids => []}, assets_attributes: [:image => [:id, :image_file_name]])
    params.require(:job).permit!
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_asset.html.erb
<div id="upload_assets">
You Can Upload
<% if ((MAX_ASSETS - @ct.to_i) < MAX_ASSETS) %>
	An Additional
<% end %>
	<%= (MAX_ASSETS - @ct.to_i) %> Image(s)
<table id="tableassets">
	<tr>
  	<%= div_for @job.assets do |asset| %>
		<% unless asset.new_record? %>
			<td>
				<table>
					<tr><td>
						<%= link_to(image_tag(asset.image.url(:thumbnail)),asset.image.url(:original))  %>
					</td></tr>
					<tr><td>
						<%= link_to "(Remove)",job_asset_path(@job.id, asset.id), data: {confirm: 'Are you sure?'}, :method => :delete, :onclick => "$(this).up('.asset').remove()" %>
					</td></tr>
				</table>
			</td>
		<% end %>
	<% end %>
		<%= f.fields_for :assets do |asset| %>
	  		<% if asset.object.new_record? %>
	  		<td>
	  			<table class="tableassets">
	  				<tr><td>
	  					<%= asset.file_field :image %>
	  				</td></tr>
	  				<tr><td>

	  				</td></tr>
	  			</table>
	  		</td>
	  		<% end %>
	  	<% end %>
	</tr>
</table>
	<%= link_to 'Hide Images', '#', :id => 'upload_assets_link', :onclick => "$('#upload_assets').slideUp();" %>
</div>

app/views/jobs/_form.html.erb
<%= form_for @job, html: { multipart: true }, :validate => true do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>&nbsp;
    <i>(hint: at least include a state abbreviation. -> i.e. CA, FL, IL, IA, NY, etc....)</i>
  </div>



   	<div class="field">
		<%= f.label "Categories" %>
		<% Category.all.each do |category| %>
			<%= check_box_tag 'job[category_ids][]', category.id, @job.categories.include?(category)%>
			<%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
		<% end %>
	</div>

  <div class="field">
    <%= f.label "Search Words" %><br />
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label "Stuff to be done" %><br />
    <%= f.text_area :body %>
  </div>


  <div class="field">
	<%= link_to 'Upload Images (Optional)*', '#', :id => 'upload_assets_link', :onclick => "$('#upload_assets').slideDown();" %>
	<%= render "asset", :f => f %>
  </div>


  <div class="actions">
    <%= submit_tag 'Let Folks Know About This Stuff' %> or
	<%= link_to 'Simmer Just A Bit!', jobs_path %>
  </div>

<% end %>

app/views/jobs/_job.html.erb
<%= div_for job do  %>
	<% @selected = job.bids.where('bid_selected = ?', 1).first%>
	<% if (current_page?("/") || current_page?(jobs_path) || current_page?(search_jobs_path)) %>
		<div class="job_wrapper">
	<% end %>
	<h3>
		<% if (current_page?("/") || current_page?(jobs_path) || current_page?(search_jobs_path)) && !job.owned_by?(current_member) & !@selected %>
			<span class="job_title"><%= link_to (job.title << " (click me to bid on this job)"), job %></span>
		<% else %>
			<span class="job_title"><%= link_to job.title, job %></span>
		<% end %>
		<% if ((Time.zone.now - job.updated_at).to_i / 1.day) > 0 %>
			<span class="actions">Posted/Updated <%= (Time.zone.now - job.updated_at).to_i / 1.day %>&nbsp;day(s) ago by <span class="color_it_green"><%= Member.find(job.member_id).email %></span></span>
		<% else %>
			<span class="actions">Posted/Updated Today by: <span class="color_it_green"><%= Member.find(job.member_id).email %></span></span>
		<% end %>

		<% if job.owned_by?(current_member) && @selected.nil? %>
			<span class="actions">
				<%= link_to "Edit/Update This Stuff", edit_job_path(job) %>|
				<%= link_to "Remove This Stuff", job, :confirm => "Are you sure?", :method => :delete %>
			</span>
		<% end %>
	</h3>
	Categories: |
	<% job.categories.each do |jobcat| %>
		<b><%= jobcat.name %> |</b>
	<% end %>
	&nbsp;Search Words:
	<b><%= job.excerpt %></b><br />

	Location:&nbsp;<b><%= job.location %></b><br />



	<table class="tableassets">
		<tr>
		  	<%= div_for job.assets do |a| %>
				<td>
					<%= link_to(image_tag(a.image.url(:thumbnail)),a.image.url(:medium))  %><br />
				</td>
			<% end %>
		</tr>
	</table>



	<% if job.bids.count > 0 %>
		<span id="current_bids">
			Current Bids On This Stuff:&nbsp;<b><%= job.bids.count %></b>
			<!--% @selected = job.bids.find(:first, :conditions => ['bid_selected == 1']) % -->
		</span>
		<% if !@selected.nil? %>
			<div class=bid_selected><%= @selected.name %>'s bid won!   -   Congratulations <%= @selected.name %>!&nbsp;&nbsp;<span class=not_accepting>Not Accepting New Bids!</span></div>
		<% end %>

	<% end %>
	<% if job.comments.count > 0 and (current_page?("/") || current_page?(jobs_path) || current_page?(search_jobs_path)) %>
		<span id="has_comments">
			<%= link_to "(click me to see stuff said about this stuff...)", job %>
		</span>
	<% end %>

	<div id="job_body">
		<% @body = job.body %>
		<% if (current_page?("/") || current_page?(jobs_path) || current_page?(search_jobs_path)) && (job.body.size > 300) %>
					&rarr;&nbsp;<%= @body[0..299] %>&nbsp;<i><%= link_to "(more...)", job %></i>
		<% else %>
			&rarr;&nbsp;<%= @body %>
		<% end %>
	</div>


	<% if (current_page?("/") || current_page?(jobs_path) || current_page?(search_jobs_path)) %>
		</div> <!-- class="job_wrapper" -->
	<% end %>
<% end %>

app/views/jobs/_limit.html.erb
<%= form_tag(limit_jobs_path, :id => 'limit_form', :style => 'display:none') do %>
<div class="field">	
   	<%= label_tag :category, "Categories:" %>
	<% for category in Category.all %>
		<%= check_box_tag 'limit[]', category.id %>
		<%= label_tag dom_id(category), category.name, :class => "check_box_label" %>	
	<% end %> &nbsp;&nbsp;
</div>

<% end %>	

app/views/jobs/_notify_friend.html.erb
<%= form_tag(notify_friend_job_path(@job), :id => 'notify_friend_form', :style =>"display: none;") do %>
	<div class="field">
		<%= label_tag :name, 'Your name'%><br />
		<%= text_field_tag :name %>
	</div>
	<div class="field">
		<%= label_tag :email, "Your friend's email"%><br />
		<%= text_field_tag :email %>
	</div>
	<div class="actions">
		<%= submit_tag 'Send It!' %> or
		<%= link_to 'Simmer A Bit More!', '#', :onclick => "$('#notify_friend_form').slideUp()" %>
	</div>
<% end %>

app/views/jobs/_search.html.erb
<%= form_tag search_jobs_path, :method => :get do %>
	<p>
		Search
		<%= text_field_tag :keyword, params[:keyword] %>&nbsp;&nbsp;		
		Category
		<%= select_tag :category, options_for_select(Category.all.collect{ |c| [c.name, c.id] }.insert(0, '*All'), params[:category]), 
		:onchange => "this.form.submit();", :remote => true  %>	
	</p>
<% end %>	

app/views/jobs/edit.html.erb
<h1>Editing stuff</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div id="jobs">
	<% if @jobs.count() > 0 %>
		<%= paginate @jobs -%>
		<%= render @jobs -%>
		<%= paginate @jobs -%>
	<% else %>
		<%= link_to 'Sorry, no search results found....', jobs_path %>
	<% end %>
</div>
<br />


<% if logged_in? %>
	<%= link_to 'I want some new stuff done.', new_job_path %>
<% end %>

app/views/jobs/new.html.erb
<h1>Create New Stuff You Want Done!</h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<div id="show_job">

	<%= render @job -%>
	<br />
	<% @selected = @job.bids.where('bid_selected = ?', 1).first %>
	<% if @selected.blank? %>
		<%= link_to 'Email A Friend About This Stuff', '#', :id => 'email_friend_link', :onclick => "$('#notify_friend_form').slideDown();" %>
		<%= render 'notify_friend' %>
	<% end %>

	<% if @selected.nil? && !@job.owned_by?(current_member) %>
		<br/>
		<%= link_to 'Bid On This Stuff', new_job_bid_path(@job, :format => :js), :remote => true, :id => 'new_bid_link' %>&nbsp;
	<% end %>

	<div id="bids">
	<% if @job.bids.count > 0 %>
		<br/><h3>Current Bids</h3>
		<%= render @job.bids.order('bid_per_rate ASC, bid_amount ASC')%>
	<% end %>
	</div>

	<div id="zzcomments">
	<% if @job.comments.count > 0 %>
		<h3 id="stuff_said_hdr">Stuff Said About This Stuff...</h3>
		<%= render @job.comments.order('updated_at DESC') %>
	<% end %>
	</div>



	<% if logged_in? %>
		<%= link_to 'Say Something About This Stuff', new_job_comment_path(@job, :format => :js), :remote => true, :id => 'new_comment_link' %>&nbsp;
	<% end %>

	<%= link_to 'Simmer Just A Bit!', jobs_path, :id => 'job_cancel_link' -%>

</div>