config/routes.rb
IWillWorkForGumbo::Application.routes.draw do

  get "pages/help"

  resources :jobs do
    member do
      post :notify_friend
    end
    collection do
      get :search
      get :limit
    end
    resources :bids
    resources :comments
    resources :assets

  end

  resources :members do
    resources :comments
  end
  resource :session
  resources :password_resets

  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  root :to => 'jobs#index'

end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>

<head>
  <title>iWillWorkForGumbo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", "rails.validations" -%>
  <%= csrf_meta_tags %>

</head>

<body id="container">
	<div style="float: right;"><%= link_to "Help", pages_help_path %></div>

	<table width="100%" padding-top="0px"><tr>


		<td>
		<div id="header">
			<%= link_to image_tag("iWillWorkForGumbox.png"), jobs_path %>
		</div>
		</td>
		<td>
		<div id="member_bar">
			<% if logged_in? %>
				<b>Welcome <%= current_member.email -%></b> |
				<%= link_to "Make New Stuff To Do", new_job_path %>|
				<%= link_to "Edit Your Member Profile", edit_member_path(current_member) %>|
				<%= link_to "Logout", logout_path %>
			<% else %>
				<%= link_to "Login", login_path %>&nbsp;or become a&nbsp;<%= link_to "New Registered Member", new_member_path %>
			<% end %><br />
			<%= render 'jobs/search' %>

		</div>
		</td>
	</tr></table>
	<div id="main">


		<h2>Folks want stuff done - Now go bid on some of it.</h2>
		<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
		<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
		<%= yield %>
	</div>
	<div id="footer">
		<%= link_to "Soup's On...", jobs_path %>
	</div>
</body>

</html>